apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
  namespace: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: charanprajwal001/nextjs-app:20250411-01   # Replace with your actual image
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
  namespace: nodejs-deployment
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3001       # Exposed service port
      targetPort: 3000  # Matches containerPort in Deployment
  type: LoadBalancer  # Use NodePort or LoadBalancer if needed
