apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
  namespace: nodejs-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: charanprajwal001/nodejs-app:latest   # Replace with your actual image
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nodejs-configmap  # Load env variables from ConfigMap

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: nodejs-deployment
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3010        # Exposed service port
      targetPort: 3000  # Matches containerPort in Deployment
  type: LoadBalancer  # Use NodePort or LoadBalancer if needed
